package com.drishti.core.agent

/**
 * The few things Aura says without asking the model, in every language it speaks.
 *
 * Everything step-specific comes from the model in the user's language; these are the
 * fixed lines around it — starting, waiting, stopping — so a Hindi speaker never hears an
 * English sentence read in a Hindi voice.
 */
enum class Phrase {
    Looking,
    StillThere,
    Paused,
    Resuming,
    LostPermission,
    SensitiveApp,
    TooManySteps,
    GoingInCircles,
    NotSure,
    NoModel,
    Offline,
    ModelError,
    TakeYourTime,
    NotQuite,
}

object Phrases {
    fun get(phrase: Phrase, language: Language): String =
        table[language]?.get(phrase) ?: table.getValue(Language.English).getValue(phrase)

    private val table: Map<Language, Map<Phrase, String>> = mapOf(
        Language.English to mapOf(
            Phrase.Looking to "Let me look",
            Phrase.StillThere to "Take your time. Look for the glowing circle.",
            Phrase.Paused to "I'll wait here. Tap me when you're ready.",
            Phrase.Resuming to "Okay, let's carry on",
            Phrase.LostPermission to "I can't see the screen. Please turn Aura back on in Accessibility settings.",
            Phrase.SensitiveApp to "This is a banking or private app, so I've stopped looking.",
            Phrase.TooManySteps to "That's as far as I can take you for now.",
            Phrase.GoingInCircles to "I'm going round in circles. Let's stop here.",
            Phrase.NotSure to "I'm not sure what to show you next.",
            Phrase.NoModel to "I'm not set up yet. Add a key in Aura's settings.",
            Phrase.Offline to "I can't reach the internet right now.",
            Phrase.ModelError to "Something went wrong on my side. Nothing was changed.",
            Phrase.TakeYourTime to "No hurry.",
            Phrase.NotQuite to "Not quite. Tap inside the glowing circle.",
        ),
        Language.Hindi to mapOf(
            Phrase.Looking to "मैं देखती हूँ",
            Phrase.StillThere to "आराम से। चमकते हुए गोले को देखिए।",
            Phrase.Paused to "मैं यहीं रुकती हूँ। तैयार हों तो मुझे छुइए।",
            Phrase.Resuming to "ठीक है, आगे चलते हैं",
            Phrase.LostPermission to "मुझे स्क्रीन नहीं दिख रही। Accessibility सेटिंग में Aura को फिर से चालू करें।",
            Phrase.SensitiveApp to "यह बैंक या निजी ऐप है, इसलिए मैंने देखना बंद कर दिया है।",
            Phrase.TooManySteps to "अभी मैं यहीं तक मदद कर सकती हूँ।",
            Phrase.GoingInCircles to "मैं एक ही जगह घूम रही हूँ। यहीं रुकते हैं।",
            Phrase.NotSure to "मुझे समझ नहीं आ रहा कि आगे क्या दिखाऊँ।",
            Phrase.NoModel to "मैं अभी तैयार नहीं हूँ। Aura की सेटिंग में key डालें।",
            Phrase.Offline to "अभी इंटरनेट से जुड़ नहीं पा रही।",
            Phrase.ModelError to "मेरी तरफ़ से कुछ गड़बड़ हुई। कुछ भी बदला नहीं गया।",
            Phrase.TakeYourTime to "कोई जल्दी नहीं।",
            Phrase.NotQuite to "यह नहीं। चमकते गोले के अंदर छुइए।",
        ),
        Language.Bengali to mapOf(
            Phrase.Looking to "আমি দেখছি",
            Phrase.StillThere to "সময় নিন। জ্বলজ্বলে বৃত্তটা খুঁজুন।",
            Phrase.Paused to "আমি এখানে অপেক্ষা করছি। তৈরি হলে আমাকে ছোঁবেন।",
            Phrase.Resuming to "ঠিক আছে, এগোই",
            Phrase.LostPermission to "আমি স্ক্রিন দেখতে পাচ্ছি না। Accessibility সেটিংসে Aura আবার চালু করুন।",
            Phrase.SensitiveApp to "এটা ব্যাংক বা ব্যক্তিগত অ্যাপ, তাই আমি দেখা বন্ধ করেছি।",
            Phrase.TooManySteps to "এখন এর বেশি আমি সাহায্য করতে পারছি না।",
            Phrase.GoingInCircles to "আমি একই জায়গায় ঘুরছি। এখানেই থামি।",
            Phrase.NotSure to "পরের ধাপ কী দেখাব বুঝতে পারছি না।",
            Phrase.NoModel to "আমি এখনও তৈরি নই। Aura-র সেটিংসে key দিন।",
            Phrase.Offline to "এখন ইন্টারনেটে যুক্ত হতে পারছি না।",
            Phrase.ModelError to "আমার দিকে কিছু ভুল হয়েছে। কিছুই বদলায়নি।",
            Phrase.TakeYourTime to "কোনো তাড়া নেই।",
            Phrase.NotQuite to "এটা নয়। জ্বলজ্বলে বৃত্তের ভেতরে ছোঁবেন।",
        ),
        Language.Telugu to mapOf(
            Phrase.Looking to "నేను చూస్తాను",
            Phrase.StillThere to "నెమ్మదిగా చూడండి. మెరుస్తున్న వృత్తాన్ని వెతకండి.",
            Phrase.Paused to "నేను ఇక్కడే ఎదురుచూస్తాను. సిద్ధమైతే నన్ను తాకండి.",
            Phrase.Resuming to "సరే, ముందుకు వెళదాం",
            Phrase.LostPermission to "నాకు స్క్రీన్ కనిపించడం లేదు. Accessibility సెట్టింగ్స్‌లో Aura‌ని మళ్లీ ఆన్ చేయండి.",
            Phrase.SensitiveApp to "ఇది బ్యాంక్ లేదా ప్రైవేట్ యాప్, అందుకే చూడటం ఆపేశాను.",
            Phrase.TooManySteps to "ప్రస్తుతానికి ఇంతవరకే సహాయం చేయగలను.",
            Phrase.GoingInCircles to "నేను అక్కడక్కడే తిరుగుతున్నాను. ఇక్కడ ఆపుదాం.",
            Phrase.NotSure to "తర్వాత ఏం చూపించాలో నాకు తెలియడం లేదు.",
            Phrase.NoModel to "నేను ఇంకా సిద్ధంగా లేను. Aura సెట్టింగ్స్‌లో key జోడించండి.",
            Phrase.Offline to "ఇప్పుడు ఇంటర్నెట్‌కి కనెక్ట్ కాలేకపోతున్నాను.",
            Phrase.ModelError to "నా వైపు ఏదో పొరపాటు జరిగింది. ఏమీ మారలేదు.",
            Phrase.TakeYourTime to "తొందర లేదు.",
            Phrase.NotQuite to "అది కాదు. మెరుస్తున్న వృత్తం లోపల తాకండి.",
        ),
        Language.Marathi to mapOf(
            Phrase.Looking to "मी पाहते",
            Phrase.StillThere to "सावकाश. चमकणारे वर्तुळ शोधा.",
            Phrase.Paused to "मी इथेच थांबते. तयार झालात की मला स्पर्श करा.",
            Phrase.Resuming to "ठीक आहे, पुढे जाऊया",
            Phrase.LostPermission to "मला स्क्रीन दिसत नाही. Accessibility सेटिंग्जमध्ये Aura पुन्हा सुरू करा.",
            Phrase.SensitiveApp to "हे बँक किंवा खाजगी ॲप आहे, म्हणून मी पाहणे थांबवले आहे.",
            Phrase.TooManySteps to "सध्या मी इथपर्यंतच मदत करू शकते.",
            Phrase.GoingInCircles to "मी त्याच ठिकाणी फिरते आहे. इथेच थांबूया.",
            Phrase.NotSure to "पुढे काय दाखवायचे ते मला समजत नाही.",
            Phrase.NoModel to "मी अजून तयार नाही. Aura च्या सेटिंग्जमध्ये key टाका.",
            Phrase.Offline to "आत्ता इंटरनेटशी जोडता येत नाही.",
            Phrase.ModelError to "माझ्याकडून काहीतरी चुकले. काहीही बदलले नाही.",
            Phrase.TakeYourTime to "घाई नाही.",
            Phrase.NotQuite to "हे नाही. चमकणाऱ्या वर्तुळाच्या आत स्पर्श करा.",
        ),
        Language.Tamil to mapOf(
            Phrase.Looking to "நான் பார்க்கிறேன்",
            Phrase.StillThere to "நிதானமாகப் பாருங்கள். ஒளிரும் வட்டத்தைத் தேடுங்கள்.",
            Phrase.Paused to "நான் இங்கே காத்திருக்கிறேன். தயாரானதும் என்னைத் தொடுங்கள்.",
            Phrase.Resuming to "சரி, தொடரலாம்",
            Phrase.LostPermission to "எனக்குத் திரை தெரியவில்லை. Accessibility அமைப்புகளில் Aura-வை மீண்டும் இயக்குங்கள்.",
            Phrase.SensitiveApp to "இது வங்கி அல்லது தனிப்பட்ட ஆப், அதனால் பார்ப்பதை நிறுத்திவிட்டேன்.",
            Phrase.TooManySteps to "இப்போதைக்கு இவ்வளவுதான் உதவ முடியும்.",
            Phrase.GoingInCircles to "நான் சுற்றிச் சுற்றி வருகிறேன். இங்கே நிறுத்தலாம்.",
            Phrase.NotSure to "அடுத்து என்ன காட்டுவது என்று தெரியவில்லை.",
            Phrase.NoModel to "நான் இன்னும் தயாராகவில்லை. Aura அமைப்புகளில் key சேர்க்கவும்.",
            Phrase.Offline to "இப்போது இணையத்துடன் இணைக்க முடியவில்லை.",
            Phrase.ModelError to "என் பக்கம் ஏதோ தவறு நடந்தது. எதுவும் மாறவில்லை.",
            Phrase.TakeYourTime to "அவசரம் இல்லை.",
            Phrase.NotQuite to "அது இல்லை. ஒளிரும் வட்டத்தின் உள்ளே தொடுங்கள்.",
        ),
        Language.Gujarati to mapOf(
            Phrase.Looking to "હું જોઉં છું",
            Phrase.StillThere to "આરામથી. ચમકતું વર્તુળ શોધો.",
            Phrase.Paused to "હું અહીં રાહ જોઉં છું. તૈયાર હો ત્યારે મને સ્પર્શ કરો.",
            Phrase.Resuming to "બરાબર, આગળ વધીએ",
            Phrase.LostPermission to "મને સ્ક્રીન દેખાતી નથી. Accessibility સેટિંગ્સમાં Aura ફરી ચાલુ કરો.",
            Phrase.SensitiveApp to "આ બેંક અથવા ખાનગી એપ છે, તેથી મેં જોવાનું બંધ કર્યું છે.",
            Phrase.TooManySteps to "હમણાં હું અહીં સુધી જ મદદ કરી શકું છું.",
            Phrase.GoingInCircles to "હું એક જ જગ્યાએ ફરું છું. અહીં અટકીએ.",
            Phrase.NotSure to "આગળ શું બતાવવું તે મને સમજાતું નથી.",
            Phrase.NoModel to "હું હજી તૈયાર નથી. Aura ની સેટિંગ્સમાં key ઉમેરો.",
            Phrase.Offline to "અત્યારે ઇન્ટરનેટ સાથે જોડાઈ શકતી નથી.",
            Phrase.ModelError to "મારી બાજુથી કંઈક ખોટું થયું. કંઈ બદલાયું નથી.",
            Phrase.TakeYourTime to "કોઈ ઉતાવળ નથી.",
            Phrase.NotQuite to "એ નહીં. ચમકતા વર્તુળની અંદર સ્પર્શ કરો.",
        ),
        Language.Kannada to mapOf(
            Phrase.Looking to "ನಾನು ನೋಡುತ್ತೇನೆ",
            Phrase.StillThere to "ನಿಧಾನವಾಗಿ. ಹೊಳೆಯುವ ವೃತ್ತವನ್ನು ಹುಡುಕಿ.",
            Phrase.Paused to "ನಾನು ಇಲ್ಲೇ ಕಾಯುತ್ತೇನೆ. ಸಿದ್ಧವಾದಾಗ ನನ್ನನ್ನು ಸ್ಪರ್ಶಿಸಿ.",
            Phrase.Resuming to "ಸರಿ, ಮುಂದುವರಿಯೋಣ",
            Phrase.LostPermission to "ನನಗೆ ಪರದೆ ಕಾಣುತ್ತಿಲ್ಲ. Accessibility ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ Aura ಅನ್ನು ಮತ್ತೆ ಆನ್ ಮಾಡಿ.",
            Phrase.SensitiveApp to "ಇದು ಬ್ಯಾಂಕ್ ಅಥವಾ ಖಾಸಗಿ ಆ್ಯಪ್, ಆದ್ದರಿಂದ ನೋಡುವುದನ್ನು ನಿಲ್ಲಿಸಿದ್ದೇನೆ.",
            Phrase.TooManySteps to "ಸದ್ಯಕ್ಕೆ ಇಷ್ಟೇ ಸಹಾಯ ಮಾಡಬಲ್ಲೆ.",
            Phrase.GoingInCircles to "ನಾನು ಒಂದೇ ಕಡೆ ಸುತ್ತುತ್ತಿದ್ದೇನೆ. ಇಲ್ಲೇ ನಿಲ್ಲಿಸೋಣ.",
            Phrase.NotSure to "ಮುಂದೆ ಏನು ತೋರಿಸಬೇಕು ಎಂದು ತಿಳಿಯುತ್ತಿಲ್ಲ.",
            Phrase.NoModel to "ನಾನು ಇನ್ನೂ ಸಿದ್ಧವಾಗಿಲ್ಲ. Aura ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ key ಸೇರಿಸಿ.",
            Phrase.Offline to "ಈಗ ಇಂಟರ್ನೆಟ್‌ಗೆ ಸಂಪರ್ಕಿಸಲು ಆಗುತ್ತಿಲ್ಲ.",
            Phrase.ModelError to "ನನ್ನ ಕಡೆಯಿಂದ ಏನೋ ತಪ್ಪಾಯಿತು. ಏನೂ ಬದಲಾಗಿಲ್ಲ.",
            Phrase.TakeYourTime to "ಅವಸರ ಇಲ್ಲ.",
            Phrase.NotQuite to "ಅದಲ್ಲ. ಹೊಳೆಯುವ ವೃತ್ತದ ಒಳಗೆ ಸ್ಪರ್ಶಿಸಿ.",
        ),
        Language.Malayalam to mapOf(
            Phrase.Looking to "ഞാൻ നോക്കട്ടെ",
            Phrase.StillThere to "പതുക്കെ മതി. തിളങ്ങുന്ന വൃത്തം നോക്കൂ.",
            Phrase.Paused to "ഞാൻ ഇവിടെ കാത്തിരിക്കാം. തയ്യാറാകുമ്പോൾ എന്നെ തൊടൂ.",
            Phrase.Resuming to "ശരി, തുടരാം",
            Phrase.LostPermission to "എനിക്ക് സ്ക്രീൻ കാണാനാകുന്നില്ല. Accessibility ക്രമീകരണങ്ങളിൽ Aura വീണ്ടും ഓണാക്കൂ.",
            Phrase.SensitiveApp to "ഇത് ബാങ്ക് അല്ലെങ്കിൽ സ്വകാര്യ ആപ്പാണ്, അതിനാൽ ഞാൻ നോക്കുന്നത് നിർത്തി.",
            Phrase.TooManySteps to "ഇപ്പോൾ ഇത്രയേ സഹായിക്കാനാകൂ.",
            Phrase.GoingInCircles to "ഞാൻ ഒരേ സ്ഥലത്ത് കറങ്ങുകയാണ്. ഇവിടെ നിർത്താം.",
            Phrase.NotSure to "അടുത്തതായി എന്ത് കാണിക്കണമെന്ന് ഉറപ്പില്ല.",
            Phrase.NoModel to "ഞാൻ ഇതുവരെ തയ്യാറായിട്ടില്ല. Aura ക്രമീകരണങ്ങളിൽ key ചേർക്കൂ.",
            Phrase.Offline to "ഇപ്പോൾ ഇന്റർനെറ്റുമായി ബന്ധിപ്പിക്കാനാകുന്നില്ല.",
            Phrase.ModelError to "എന്റെ ഭാഗത്ത് എന്തോ പിഴവ് പറ്റി. ഒന്നും മാറിയിട്ടില്ല.",
            Phrase.TakeYourTime to "ധൃതിയില്ല.",
            Phrase.NotQuite to "അതല്ല. തിളങ്ങുന്ന വൃത്തത്തിനുള്ളിൽ തൊടൂ.",
        ),
        Language.Punjabi to mapOf(
            Phrase.Looking to "ਮੈਂ ਵੇਖਦੀ ਹਾਂ",
            Phrase.StillThere to "ਆਰਾਮ ਨਾਲ। ਚਮਕਦਾ ਗੋਲਾ ਲੱਭੋ।",
            Phrase.Paused to "ਮੈਂ ਇੱਥੇ ਉਡੀਕ ਕਰਦੀ ਹਾਂ। ਤਿਆਰ ਹੋਵੋ ਤਾਂ ਮੈਨੂੰ ਛੂਹੋ।",
            Phrase.Resuming to "ਠੀਕ ਹੈ, ਅੱਗੇ ਚੱਲੀਏ",
            Phrase.LostPermission to "ਮੈਨੂੰ ਸਕ੍ਰੀਨ ਨਹੀਂ ਦਿਸ ਰਹੀ। Accessibility ਸੈਟਿੰਗਾਂ ਵਿੱਚ Aura ਮੁੜ ਚਾਲੂ ਕਰੋ।",
            Phrase.SensitiveApp to "ਇਹ ਬੈਂਕ ਜਾਂ ਨਿੱਜੀ ਐਪ ਹੈ, ਇਸ ਲਈ ਮੈਂ ਵੇਖਣਾ ਬੰਦ ਕਰ ਦਿੱਤਾ ਹੈ।",
            Phrase.TooManySteps to "ਹਾਲੇ ਮੈਂ ਇੱਥੋਂ ਤੱਕ ਹੀ ਮਦਦ ਕਰ ਸਕਦੀ ਹਾਂ।",
            Phrase.GoingInCircles to "ਮੈਂ ਇੱਕੋ ਥਾਂ ਘੁੰਮ ਰਹੀ ਹਾਂ। ਇੱਥੇ ਰੁਕਦੇ ਹਾਂ।",
            Phrase.NotSure to "ਮੈਨੂੰ ਸਮਝ ਨਹੀਂ ਆ ਰਿਹਾ ਕਿ ਅੱਗੇ ਕੀ ਦਿਖਾਵਾਂ।",
            Phrase.NoModel to "ਮੈਂ ਹਾਲੇ ਤਿਆਰ ਨਹੀਂ ਹਾਂ। Aura ਦੀਆਂ ਸੈਟਿੰਗਾਂ ਵਿੱਚ key ਪਾਓ।",
            Phrase.Offline to "ਹੁਣੇ ਇੰਟਰਨੈੱਟ ਨਾਲ ਨਹੀਂ ਜੁੜ ਪਾ ਰਹੀ।",
            Phrase.ModelError to "ਮੇਰੇ ਵੱਲੋਂ ਕੁਝ ਗੜਬੜ ਹੋਈ। ਕੁਝ ਵੀ ਨਹੀਂ ਬਦਲਿਆ।",
            Phrase.TakeYourTime to "ਕੋਈ ਕਾਹਲੀ ਨਹੀਂ।",
            Phrase.NotQuite to "ਇਹ ਨਹੀਂ। ਚਮਕਦੇ ਗੋਲੇ ਦੇ ਅੰਦਰ ਛੂਹੋ।",
        ),
        Language.Odia to mapOf(
            Phrase.Looking to "ମୁଁ ଦେଖୁଛି",
            Phrase.StillThere to "ଧୀରେ ଧୀରେ। ଚମକୁଥିବା ବୃତ୍ତଟି ଖୋଜନ୍ତୁ।",
            Phrase.Paused to "ମୁଁ ଏଠାରେ ଅପେକ୍ଷା କରୁଛି। ପ୍ରସ୍ତୁତ ହେଲେ ମୋତେ ଛୁଅଁନ୍ତୁ।",
            Phrase.Resuming to "ଠିକ ଅଛି, ଆଗକୁ ଯିବା",
            Phrase.LostPermission to "ମୁଁ ସ୍କ୍ରିନ ଦେଖିପାରୁନାହିଁ। Accessibility ସେଟିଂସରେ Aura ପୁଣି ଚାଲୁ କରନ୍ତୁ।",
            Phrase.SensitiveApp to "ଏହା ବ୍ୟାଙ୍କ ବା ବ୍ୟକ୍ତିଗତ ଆପ୍, ତେଣୁ ମୁଁ ଦେଖିବା ବନ୍ଦ କରିଛି।",
            Phrase.TooManySteps to "ବର୍ତ୍ତମାନ ମୁଁ ଏତିକି ପର୍ଯ୍ୟନ୍ତ ସାହାଯ୍ୟ କରିପାରିବି।",
            Phrase.GoingInCircles to "ମୁଁ ଗୋଟିଏ ଜାଗାରେ ଘୂରୁଛି। ଏଠାରେ ରହିବା।",
            Phrase.NotSure to "ପରେ କଣ ଦେଖାଇବି ମୁଁ ବୁଝିପାରୁନାହିଁ।",
            Phrase.NoModel to "ମୁଁ ଏପର୍ଯ୍ୟନ୍ତ ପ୍ରସ୍ତୁତ ନୁହେଁ। Aura ସେଟିଂସରେ key ଦିଅନ୍ତୁ।",
            Phrase.Offline to "ଏବେ ଇଣ୍ଟରନେଟ ସହ ଯୋଡି ହେଉନାହିଁ।",
            Phrase.ModelError to "ମୋ ପକ୍ଷରୁ କିଛି ଭୁଲ ହେଲା। କିଛି ବଦଳିନାହିଁ।",
            Phrase.TakeYourTime to "କୌଣସି ତରବର ନାହିଁ।",
            Phrase.NotQuite to "ଏହା ନୁହେଁ। ଚମକୁଥିବା ବୃତ୍ତ ଭିତରେ ଛୁଅଁନ୍ତୁ।",
        ),
    )
}
